# Jekyll configuration for GitHub Pages
# This file helps GitHub Pages understand your site structure

# Site settings
title: Celes Chai
description: Personal website showcasing work, research, and professional experience
author: Celes Chai
email: celes.chai@example.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Collections
collections:
  posts:
    output: true
    permalink: /:collection/:title/

# Plugins (GitHub Pages compatible)
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - README.md
  - _config.yml
  - .gitignore
  - node_modules
  - package.json
  - package-lock.json

# Include files
include:
  - _includes
  - _layouts
  - _sass
  - assets

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Celes Chai"

# Sitemap settings
sitemap:
  exclude:
    - /404.html
    - /robots.txt
